### ISSUE TITLE
Bot is taking lot of memory?

### ISSUE THREAD

**Issue by samdivaio** [jagrosh/Selfbot#14]
Bot happens to take almost ~40% of memory on an 1gig vps. Tested on a fresh DigitalOcean droplet.

**Comment by SteamingMutt** [comment]
The amount of RAM selfbot uses depends on how many servers you're in, how many users you can 'see' at any given time, and how many channels exist across all your servers (regardless if you can access them or not).
I would suggest providing these metrics with this issue.

**Comment by jagrosh** [comment]
Other things that would also contribute to using more memory:
* Number of friends/pending friends/blocked users
* Number of open DMs
* Number of members/roles/channels/permission overrides/etc for all guilds you are in

Also, keep in mind that the JVM (Java Virtual Machine) assigns itself memory to work with, even if it's not necessarily using all of it. I don't recommend changing any settings (as usually it does best if allowed to expand + contract on its own), but you can use the `-Xmx200m` flag (for example) to limit it to 200mb. I would say to avoid this though, because the bot might fail to load or stop responding if it cannot load everything it needs.

**Comment by samdivaio** [comment]
I guess its just normal Java thing. 
These are the details:
- 42 servers (563 channels) (42937 users)
- 60 friends (12 online)
Bot is using:
```rt=Java.type("java.lang.Runtime").getRuntime();total=rt.totalMemory()/1024/1024;used=total - (rt.freeMemory()/1024/1024);str=used+"mb / "+total+"mb"; ```
Evaluated Successfully:
```229.20294189453125mb / 247.5mb``` thanks @shikhir-arora to help me find these details.
